.\" .md5sum(5) manual page
.\" See COPYING and COPYRIGHT files for corresponding information.
.Dd January 26, 2025
.Dt PKGMK.MD5SUM 5
.Os
.\" ==================================================================
.Sh NAME
.Nm pkgmk.md5sum
.Nd MD5 checksums of pkgmk's source files
.\" ==================================================================
.Sh SYNOPSIS
.Nm .md5sum
.\" ==================================================================
.Sh DESCRIPTION
This manual page describes the format of the
.Pa .md5sum
files, which are used by
.Xr pkgmk 8
for ...
.Pp
TODO
.\" vim: cc=72 tw=70
.\" End of file.
