.\" pkgmk.conf(5) manual page
.\" See COPYING and COPYRIGHT files for corresponding information.
.Dd September 6, 2023
.Dt PKGMK.CONF 5
.Os
.\" ==================================================================
.Sh NAME
.Nm pkgmk.conf
.Nd configuration file for pkgmk
.\" ==================================================================
.Sh SYNOPSIS
.Nm /etc/pkgmk.conf
.\" ==================================================================
.Sh DESCRIPTION
This manual page describes the format of the
.Pa pkgmk.conf
file.
This file is a simple shell file that configures
.Xr pkgmk 8 .
The file consists of a number of variable assignments of the form
.Dq option=value .
Comments can be specified by putting a hash
.Pq Ql #
symbol as the first character on the line.
.Pp
If some option is not used (commented out or not included in the
configuration file at all)
.Xr pkgmk 8
will take a default action.
.Pp
The configuration options are as follows:
.Bl -tag -width Ds
.It Sy export CFLAGS Ns = Ns Aq STRING
Set C compiler options.
Unset by default.
.It Sy export CXXFLAGS Ns = Ns Aq STRING
Set C++ compiler options.
Unset by default.
.It Sy export JOBS Ns = Ns Aq NUMBER
Set the number of commands to run simultaneously when building a
package.
Unset by default.
.It Sy export MAKEFLAGS Ns = Ns Aq STRING
Set
.Xr make 1
options.
Unset by default.
.It Sy PKGMK_SOURCE_MIRRORS Ns = Ns Aq URI ...
Set mirrors to check and download source archives from.
If the URI contains space symbol, replace it by
.Ql %20 .
Unset by default.
.It Sy PKGMK_SOURCE_DIR Ns = Ns Aq DIR
Set directory for downloaded source archives.
By default, the current directory where
.Pa Pkgfile
is located.
.It Sy PKGMK_PACKAGE_DIR Ns = Ns Aq DIR
Set directory for built packages.
By default, the current directory where
.Pa Pkgfile
is located.
.It Sy PKGMK_WORK_DIR Ns = Ns Aq DIR
Set directory for building packages.
By default
.Dq Sy foo Ns /work ,
where
.Sy foo
is the current directory where
.Pa Pkgfile
is located.
.It Sy PKGMK_DOWNLOAD Ns = Ns Aq yes | no
Download the source archives if necessary.
By default is set to
.Dq no .
.It Sy PKGMK_DOWNLOAD_PROG Ns = Ns Aq aria2c | curl | wget
Use specified program to download source archives.
By default is set to
.Dq curl .
.It Sy PKGMK_ARIA2C_OPTS Ns = Ns Aq STRING
Additional options for
.Xr aria2c 1 ,
which is used by
.Xr pkgmk 8
to download all files.
Unset by default.
.It Sy PKGMK_CURL_OPTS Ns = Ns Aq STRING
Additional options for
.Xr curl 1 ,
which is used by
.Xr pkgmk 8
to download all files.
Unset by default.
.It Sy PKGMK_WGET_OPTS Ns = Ns Aq STRING
Additional options for
.Xr wget 1 ,
which is used by
.Xr pkgmk 8
to download all files.
Unset by default.
.It Sy PKGMK_IGNORE_FOOTPRINT Ns = Ns Aq yes | no
Perform a footprint check of the built package.
By default is set to
.Dq no .
.It Sy PKGMK_IGNORE_MD5SUM Ns = Ns Aq yes | no
Perform a md5sum check of the source archives.
By default is set to
.Dq no .
.It Sy PKGMK_IGNORE_NEW Ns = Ns Aq yes | no
Ignore new files in a footprint mismatch.
By default is set to
.Dq no .
.It Sy PKGMK_NO_STRIP Ns = Ns Aq yes | no
If set to
.Dq no ,
.Xr pkgmk 8
will strip built binaries.
By default is set to
.Dq no .
.It Sy PKGMK_COMPRESSION_MODE Ns = Ns Aq gz | bz2 | xz | lz
Option to select the mode used to compress the packages.
By default is set to
.Dq gz .
.El
.\" ==================================================================
.Sh FILES
.Bl -tag -width Ds
.It Pa /etc/pkgmk.conf
Default configuration file for
.Xr pkgmk 8 .
.El
.\" ==================================================================
.Sh EXAMPLES
.Bd -literal
#
# /etc/pkgmk.conf: pkgmk(8) configuration
#
# See pkgmk.conf(5) for more information.
#

export CFLAGS="-O2 -march=x86-64 -pipe -fdiagnostics-color=always"
export CXXFLAGS="$CFLAGS"
export JOBS=$(getconf _NPROCESSORS_ONLN)
export MAKEFLAGS="-j $JOBS"

case $PKGMK_ARCH in
"64"|"")
        ;;
"32")
        export CFLAGS="$CFLAGS -m32"
        export CXXFLAGS="$CXXFLAGS -m32"
        export LDFLAGS="$LDFLAGS -m32"
        export PKG_CONFIG_LIBDIR="/usr/lib32/pkgconfig"
        ;;
*)
        error "Unknown architecture selected! Exiting."
        exit $E_GENERAL
        ;;
esac

# End of file.
.Ed
.\" ==================================================================
.Sh SEE ALSO
.Xr Pkgfile 5 ,
.Xr pkgmk 8
.\" vim: cc=72 tw=70
.\" End of file.
